on:
  push:
    branches: ["main"] # Se déclenche lors d'un push sur la branche main

jobs:
  build:
    runs-on: ubuntu-latest # Utilise la dernière version d'Ubuntu comme environnement d'exécution

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    
    # Étape 1: Initialisation de l'environnement
    - name: Create env
      run: make init

    # Étape 2: Installation des dépendances
    - name: Install dependencies
      run: make install
        
    # Étape 3: Construction de l'image Docker
    - name: Build Docker image
      run: make build
        
    # Étape 4: Démarrage du conteneur Docker
    - name: Start Docker 
      run: make run
        
    # Étape 5: Exécution des tests API
    - name: Run tests
      run: make test-api

    # Étape 6: Exécution de l'application pour les tests
    - name: Run App
      run: make test
